Update witness.cpp
CHMEXToday at 11:09 PM
thanks that worked!
now stuck on this one
wallet/witness.cpp:328:63: error: invalid conversion from ‘UniValue (*)(const UniValue&, bool)’ to ‘rpcfn_type {aka UniValue (*)(const UniValue&, bool, const CPubKey&)}’ [-fpermissive]
ForgeToday at 11:12 PM
that one I'm not familiar with. I don't know what rpcfn_type is.
CHMEXToday at 11:16 PM
Ok thanks I try to find out
ForgeToday at 11:31 PM
i think you just need to add ", const CPubKey& mypk" 
to 
UniValue getsaplingwitness(const UniValue& params, bool fHelp)

like this

UniValue getsaplingwitness(const UniValue& params, bool fHelp,  const CPubKey& mypk)
for all 3 functions