Update witness.cpp
CHMEXToday at 11:38 PM
super that worked! thank you very much
any idea what
error: no matching function for call to ‘ReadBlockFromDisk(CBlock&, CBlockIndex*&)’
ReadBlockFromDisk is called in komodo?
ForgeToday at 11:45 PM
komodo's got  a bool checkPOW flag at the end on this, for this purpose i think it's ok to set it to false.
bool ReadBlockFromDisk(CBlock& block, const CBlockIndex* pindex,bool checkPOW)